spring.datasource.url=jdbc:postgresql://dpg-d925r2dckfvc73d8ks90-a:5432/simfinity_db
spring.datasource.username=simfinity_db_user
spring.datasource.password=wnamZmcChodcLffUrIjbHWX4kOvrV5Tq

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}
jwt.secret=${JWT_SECRET}
paystack.secret=${PAYSTACK_SECRET}
